name: CI

on:
  push:
    branches: [ main, feat/calculator-tests-ci ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Black (check)
        run: python -m black --check .

      - name: Flake8
        run: python -m flake8

      - name: Mypy
        run: python -m mypy --install-types --non-interactive .

      - name: Pytest
        run: python -m pytest -q
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Black (check)
        run: python -m black --check .

      - name: Flake8
        run: python -m flake8

      - name: Mypy
        run: python -m mypy --install-types --non-interactive .

      - name: Pytest
        run: python -m pytest -q
